<header class="header" id="header" role="banner">
	<div class="header__top">
		
		<!-- <h1 class="header__logo"><a href="/"><img src="/assets/images/logo-header01.png" class="fluid-image" alt="NEXT DESIGN"></a></h1>		<div class="header__nav">
			<ul class="nav-global clearfix">
				<li><a href="#concept"><span>コンセプト</span></a></li>
				<li><a href="#feature"><span>特長</span></a></li>
				<li><a href="#function"><span>機能</span></a></li>
				<li><a href="#case"><span>事例</span></a></li>
				<li><a href="#requirements"><span>動作環境</span></a></li>
				<li><a href="#contact"><span>お問い合わせ</span></a></li>
				<li><a href="http://www.denso-create.jp/" target="_blank"><img src="/assets/images/denso_logo.png" alt="株式会社デンソークリエイト" class="header__denso-logo"></a></li>
			</ul>
			<p class="header__icn js-show-menu"><span></span><span></span><span></span></p>
		</div> -->
	</div>
	<!-- <div class="header__dropdown js-menu-content">
		<div class="header__dropdown__inner">
			<div class="header__dropdown__head">
				<p class="header__dropdown__icn js-close-menu"><span></span><span></span></p>
				<p class="header__dropdown__logo"><a href="/"><img src="/assets/images/logo-header01.png" class="fluid-image" alt="NEXT DESIGN"></a></p>
			</div>
			<ul class="header__nav-global">
				<li><a href="#concept" class="js-nav-anchor">コンセプト</a></li>
				<li><a href="#feature" class="js-nav-anchor">特長</a></li>
				<li><a href="#function" class="js-nav-anchor">機能</a></li>
				<li><a href="#case" class="js-nav-anchor">事例</a></li>
				<li><a href="#requirements" class="js-nav-anchor">動作環境</a></li>
				<li><a href="#contact" class="js-nav-anchor">お問い合わせ</a></li>
				<li><a href="http://www.denso-create.jp/" target="_blank"><img src="/assets/images/denso_logo.png" alt="株式会社デンソークリエイト" class="header__denso-logo"></a></li>
			</ul>
		</div>
	</div> -->
</header>